name: "Update data"
on:
  schedule:
    - cron: '15 */6 * * *'
  push:
    branches:
      - 'main'

jobs:
  pull-data:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: '1.17.13'

      - name: Pull data
        run: |
          ./.script/pull.sh

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v5.0.0

      - name: Commit
        run: |
          git config user.name github-actions
          git add .
          
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "feat: update data"
            git rebase main
            git push origin main
            git tag $(./.script/version.sh minor)
            git push origin --tags
          fi
